//--------------------------------------------------
//  
//      Verilog code generated by Graphical Design
//
//  Design Unit:
//  ------------
//      Library Name      :  ruvent_rdma
//      Unit    Name      :  rdma_top
//      Unit    Type      :  Block Diagram
//      Unit    Owner     :  Ruven Torok
//  
//      Creation Date :  Thu Sep 28 20:36:13 2017
//      Version       :  Version 1.1
//  
//----------------------------------------------------

module rdma_top (
    // DEBUG INTERFACE PIN
   interface_dbg_bus,
         
   // SM DEBUG INTERFACE PIN
   sm_dbg_bus,
        	// OUTPUT PORTS
	mem2p0_rx_ready_, mem2p0_tx_bad_crc_, mem2p0_tx_data, mem2p0_tx_desc, 
	mem2p0_tx_eop_, mem2p0_tx_load_, mem2p0_tx_mod, mem2p0_tx_sop_, 
	mem2p1_rx_ready_, mem2p1_tx_bad_crc_, mem2p1_tx_data, mem2p1_tx_desc, 
	mem2p1_tx_eop_, mem2p1_tx_load_, mem2p1_tx_mod, mem2p1_tx_sop_, 
	mem2pa_rx_ready_, mem2pa_tx_bad_crc_, mem2pa_tx_data, mem2pa_tx_desc, 
	mem2pa_tx_eop_, mem2pa_tx_load_, mem2pa_tx_mod, mem2pa_tx_sop_, 
	mem2pp_rx_ready_, mem2pp_tx_bad_crc_, mem2pp_tx_data, mem2pp_tx_desc, 
	mem2pp_tx_eop_, mem2pp_tx_load_, mem2pp_tx_mod, mem2pp_tx_sop_, rdm2apb_prdata, 
	rdm2apb_pready, rdm2axi_araddr, rdm2axi_arburst, rdm2axi_arcache, rdm2axi_arid, 
	rdm2axi_arlen, rdm2axi_arlock, rdm2axi_armstr, rdm2axi_arprot, rdm2axi_arqos, 
	rdm2axi_arsize, rdm2axi_aruser, rdm2axi_arvalid, rdm2axi_awaddr, 
	rdm2axi_awburst, rdm2axi_awcache, rdm2axi_awid, rdm2axi_awlen, rdm2axi_awlock, 
	rdm2axi_awmstr, rdm2axi_awprot, rdm2axi_awqos, rdm2axi_awsize, rdm2axi_awuser, 
	rdm2axi_awvalid, rdm2axi_bready, rdm2axi_rready, rdm2axi_wdata, rdm2axi_wid, 
	rdm2axi_wlast, rdm2axi_wstrb, rdm2axi_wvalid, rdm2p_global_xoff_, rdm2p_pause_, 
	rdm2p_pfc_bus0, rdm2p_pfc_bus1, rdm2p_pfc_bus2, rdm2p_pfc_valid_, 
	// INPUT PORTS
	apb2rdm_paddr, apb2rdm_penable, apb2rdm_psel, apb2rdm_pwdata, apb2rdm_pwrite, 
	axi2rdm_arready, axi2rdm_awready, axi2rdm_bid, axi2rdm_bresp, axi2rdm_bvalid, 
	axi2rdm_rdata, axi2rdm_rid, axi2rdm_rlast, axi2rdm_rresp, axi2rdm_rvalid, 
	axi2rdm_wready, p02mem_rx_data, p02mem_rx_desc, p02mem_rx_eop_, 
	p02mem_rx_load_, p02mem_rx_sop_, p02mem_sop_rx_desc, p02mem_tx_ready_, 
	p12mem_rx_data, p12mem_rx_desc, p12mem_rx_eop_, p12mem_rx_load_, 
	p12mem_rx_sop_, p12mem_sop_rx_desc, p12mem_tx_ready_, pa2mem_rx_data, 
	pa2mem_rx_desc, pa2mem_rx_eop_, pa2mem_rx_load_, pa2mem_rx_sop_, 
	pa2mem_sop_rx_desc, pa2mem_tx_ready_, pp2mem_rx_data, pp2mem_rx_desc, 
	pp2mem_rx_eop_, pp2mem_rx_load_, pp2mem_rx_sop_, pp2mem_sop_rx_desc, 
	pp2mem_tx_ready_, rdma_clk, rdma_reset_
	);

	localparam NO_OF_RAMS = 8;

	// output ports
       // State Machines DEBUG PINS Declaration
  output [61*8-1:0] sm_dbg_bus;
  wire [61*8-1:0] sm_dbg_bus;
       // INTERFACE DEBUG PINS Declaration
  output [5*325-1:0] interface_dbg_bus;
  wire [5*325-1:0] interface_dbg_bus;
	output mem2p0_rx_ready_;
	wire mem2p0_rx_ready_;
	output mem2p0_tx_bad_crc_;
	wire mem2p0_tx_bad_crc_;
	output [255:0] mem2p0_tx_data;
	wire [255:0] mem2p0_tx_data;
	output [88:17] mem2p0_tx_desc;
	wire [88:17] mem2p0_tx_desc;
	output mem2p0_tx_eop_;
	wire mem2p0_tx_eop_;
	output mem2p0_tx_load_;
	wire mem2p0_tx_load_;
	output [4:0] mem2p0_tx_mod;
	wire [4:0] mem2p0_tx_mod;
	output mem2p0_tx_sop_;
	wire mem2p0_tx_sop_;
	output mem2p1_rx_ready_;
	wire mem2p1_rx_ready_;
	output mem2p1_tx_bad_crc_;
	wire mem2p1_tx_bad_crc_;
	output [255:0] mem2p1_tx_data;
	wire [255:0] mem2p1_tx_data;
	output [88:17] mem2p1_tx_desc;
	wire [88:17] mem2p1_tx_desc;
	output mem2p1_tx_eop_;
	wire mem2p1_tx_eop_;
	output mem2p1_tx_load_;
	wire mem2p1_tx_load_;
	output [4:0] mem2p1_tx_mod;
	wire [4:0] mem2p1_tx_mod;
	output mem2p1_tx_sop_;
	wire mem2p1_tx_sop_;
	output mem2pa_rx_ready_;
	wire mem2pa_rx_ready_;
	output mem2pa_tx_bad_crc_;
	wire mem2pa_tx_bad_crc_;
	output [63:0] mem2pa_tx_data;
	wire [63:0] mem2pa_tx_data;
	output [88:17] mem2pa_tx_desc;
	wire [88:17] mem2pa_tx_desc;
	output mem2pa_tx_eop_;
	wire mem2pa_tx_eop_;
	output mem2pa_tx_load_;
	wire mem2pa_tx_load_;
	output [2:0] mem2pa_tx_mod;
	wire [2:0] mem2pa_tx_mod;
	output mem2pa_tx_sop_;
	wire mem2pa_tx_sop_;
	output mem2pp_rx_ready_;
	wire mem2pp_rx_ready_;
	output mem2pp_tx_bad_crc_;
	wire mem2pp_tx_bad_crc_;
	output [63:0] mem2pp_tx_data;
	wire [63:0] mem2pp_tx_data;
	output [88:17] mem2pp_tx_desc;
	wire [88:17] mem2pp_tx_desc;
	output mem2pp_tx_eop_;
	wire mem2pp_tx_eop_;
	output mem2pp_tx_load_;
	wire mem2pp_tx_load_;
	output [2:0] mem2pp_tx_mod;
	wire [2:0] mem2pp_tx_mod;
	output mem2pp_tx_sop_;
	wire mem2pp_tx_sop_;
	output [31:0] rdm2apb_prdata;
	wire [31:0] rdm2apb_prdata;
	output rdm2apb_pready;
	wire rdm2apb_pready;
	output [63:0] rdm2axi_araddr;
	wire [63:0] rdm2axi_araddr;
	output [1:0] rdm2axi_arburst;
	wire [1:0] rdm2axi_arburst;
	output [3:0] rdm2axi_arcache;
	wire [3:0] rdm2axi_arcache;
	output [5:0] rdm2axi_arid;
	wire [5:0] rdm2axi_arid;
	output [4:0] rdm2axi_arlen;
	wire [4:0] rdm2axi_arlen;
	output rdm2axi_arlock;
	wire rdm2axi_arlock;
	output [1:0] rdm2axi_armstr;
	wire [1:0] rdm2axi_armstr;
	output rdm2axi_arprot;
	wire rdm2axi_arprot;
	output [3:0] rdm2axi_arqos;
	wire [3:0] rdm2axi_arqos;
	output [2:0] rdm2axi_arsize;
	wire [2:0] rdm2axi_arsize;
	output [15:0] rdm2axi_aruser;
	wire [15:0] rdm2axi_aruser;
	output rdm2axi_arvalid;
	wire rdm2axi_arvalid;
	output [63:0] rdm2axi_awaddr;
	wire [63:0] rdm2axi_awaddr;
	output [1:0] rdm2axi_awburst;
	wire [1:0] rdm2axi_awburst;
	output [3:0] rdm2axi_awcache;
	wire [3:0] rdm2axi_awcache;
	output [5:0] rdm2axi_awid;
	wire [5:0] rdm2axi_awid;
	output [4:0] rdm2axi_awlen;
	wire [4:0] rdm2axi_awlen;
	output rdm2axi_awlock;
	wire rdm2axi_awlock;
	output [1:0] rdm2axi_awmstr;
	wire [1:0] rdm2axi_awmstr;
	output rdm2axi_awprot;
	wire rdm2axi_awprot;
	output [3:0] rdm2axi_awqos;
	wire [3:0] rdm2axi_awqos;
	output [2:0] rdm2axi_awsize;
	wire [2:0] rdm2axi_awsize;
	output [15:0] rdm2axi_awuser;
	wire [15:0] rdm2axi_awuser;
	output rdm2axi_awvalid;
	wire rdm2axi_awvalid;
	output rdm2axi_bready;
	wire rdm2axi_bready;
	output rdm2axi_rready;
	wire rdm2axi_rready;
	output [255:0] rdm2axi_wdata;
	wire [255:0] rdm2axi_wdata;
	output [5:0] rdm2axi_wid;
	wire [5:0] rdm2axi_wid;
	output rdm2axi_wlast;
	wire rdm2axi_wlast;
	output [31:0] rdm2axi_wstrb;
	wire [31:0] rdm2axi_wstrb;
	output rdm2axi_wvalid;
	wire rdm2axi_wvalid;
	output rdm2p_global_xoff_;
	wire rdm2p_global_xoff_;
	output [2:0] rdm2p_pause_;
	wire [2:0] rdm2p_pause_;
	output [13:0] rdm2p_pfc_bus0;
	wire [13:0] rdm2p_pfc_bus0;
	output [13:0] rdm2p_pfc_bus1;
	wire [13:0] rdm2p_pfc_bus1;
	output [13:0] rdm2p_pfc_bus2;
	wire [13:0] rdm2p_pfc_bus2;
	output [2:0] rdm2p_pfc_valid_;
	wire [2:0] rdm2p_pfc_valid_;

	// input ports
	input [31:2] apb2rdm_paddr;
	input apb2rdm_penable;
	input apb2rdm_psel;
	input [31:0] apb2rdm_pwdata;
	input apb2rdm_pwrite;
	input axi2rdm_arready;
	input axi2rdm_awready;
	input [5:0] axi2rdm_bid;
	input [1:0] axi2rdm_bresp;
	input axi2rdm_bvalid;
	input [255:0] axi2rdm_rdata;
	input [5:0] axi2rdm_rid;
	input axi2rdm_rlast;
	input [1:0] axi2rdm_rresp;
	input axi2rdm_rvalid;
	input axi2rdm_wready;
	input [255:0] p02mem_rx_data;
	input [15:0] p02mem_rx_desc;
	input p02mem_rx_eop_;
	input p02mem_rx_load_;
	input p02mem_rx_sop_;
	input [39:7] p02mem_sop_rx_desc;
	input p02mem_tx_ready_;
	input [255:0] p12mem_rx_data;
	input [15:0] p12mem_rx_desc;
	input p12mem_rx_eop_;
	input p12mem_rx_load_;
	input p12mem_rx_sop_;
	input [39:7] p12mem_sop_rx_desc;
	input p12mem_tx_ready_;
	input [63:0] pa2mem_rx_data;
	input [15:0] pa2mem_rx_desc;
	input pa2mem_rx_eop_;
	input pa2mem_rx_load_;
	input pa2mem_rx_sop_;
	input [39:7] pa2mem_sop_rx_desc;
	input pa2mem_tx_ready_;
	input [63:0] pp2mem_rx_data;
	input [15:0] pp2mem_rx_desc;
	input pp2mem_rx_eop_;
	input pp2mem_rx_load_;
	input pp2mem_rx_sop_;
	input [39:7] pp2mem_sop_rx_desc;
	input pp2mem_tx_ready_;
	input rdma_clk;
	input rdma_reset_;

	// internal nets
	wire [100:0] axi2all_ordrd_rd_rspns_id;
	wire [15:0] axi2all_ordrd_wr_rspns_id;
	wire [255:0] axi2all_rd_rspns_data;
	wire [4:0] axi2all_rd_rspns_dphase_count;
	wire [100:0] axi2all_rd_rspns_id;
	wire axi2all_rd_rspns_last;
	wire axi2intrpt_ordrd_wr_rspns_vld;
	wire axi2intrpt_wr_ack;
	wire axi2rx_bm_ordrd_rd_ind_vld;
	wire axi2rx_bm_rd_ack;
	wire axi2rx_bm_rd_rspns_vld;
	wire axi2rx_descr_ordrd_wr_rspns_vld;
	wire axi2rx_descr_wr_ack;
	wire axi2rx_dma_wr_ordrd_wr_rspns_vld;
	wire axi2rx_dma_wr_wr_ack;
	wire [31:0] axi2slv_prdata;
	wire axi2slv_pready;
	wire axi2tx_descr_ordrd_rd_ind_vld;
	wire axi2tx_descr_rd_ack;
	wire axi2tx_descr_rd_rspns_vld;
	wire axi2tx_pkt_ordrd_rd_ind_vld;
	wire axi2tx_pkt_rd_ack;
	wire axi2tx_pkt_rd_rspns_vld;
	wire axi2tx_rdma_rd_ordrd_rd_ind_vld;
	wire axi2tx_rdma_rd_rd_ack;
	wire axi2tx_rdma_rd_rd_rspns_vld;
	wire clk;
	wire [5:0] conf_axi_max_no_of_data_phases;
	wire [6:0] conf_axi_max_reads;
	wire [6:0] conf_axi_max_writes;
	wire conf_credit_en;
	wire conf_p0_dsa_long;
	wire conf_p0_dsa_short;
	wire [47:0] conf_p0_mac_addr;
	wire conf_p0_mrvl_hdr;
	wire [13:0] conf_p0_mtu;
	wire conf_p1_dsa_long;
	wire conf_p1_dsa_short;
	wire [47:0] conf_p1_mac_addr;
	wire conf_p1_mrvl_hdr;
	wire [13:0] conf_p1_mtu;
	wire conf_p2_dsa_long;
	wire conf_p2_dsa_short;
	wire [47:0] conf_p2_mac_addr;
	wire conf_p2_mrvl_hdr;
	wire [13:0] conf_p2_mtu;
	wire [1024*16-1:0] conf_p_keys;
	wire [1024*3-1:0] conf_pmtu;
	wire [2:0] conf_port_active;
	wire [1023:0] conf_qp_vld;
	wire [15:0] conf_rocky_udp_port_no;
	wire conf_single_pkt_retry;
	wire [13:5] conf_tx_fifo_thresh;
	wire gop_int_overrun;
	wire [63:0] intrpt2axi_addr;
	wire [255:0] intrpt2axi_data;
	wire [15:0] intrpt2axi_id;
	wire [4:0] intrpt2axi_len;
	wire intrpt2axi_ordrd_wr_rspns_rdy;
	wire [9:0] intrpt2axi_qp_no;
	wire [1:0] intrpt2axi_snp;
	wire intrpt2axi_wr_req;
	wire [31:0] intrpt2axi_wr_strb;
	reg [7:0] ram_no_with_parity_error;
	reg ram_parity_error;
	wire [7:0] rams_parity_error_bus_;
	wire reset_;
	wire [63:0] rx2axi_descr_addr;
	wire [255:0] rx2axi_descr_data;
	wire [15:0] rx2axi_descr_id;
	wire [4:0] rx2axi_descr_len;
	wire [9:0] rx2axi_descr_qp_no;
	wire [1:0] rx2axi_descr_snp;
	wire rx2axi_descr_wr_req;
	wire [31:0] rx2slv_prdata;
	wire rx2slv_pready;
	wire [9:0] rx2statistics_qno;
	wire [3:0] rx2statistics_type;
	wire rx2statistics_vld;
	wire [7:0] rx2tx_mem_access_line_no;
	wire rx2tx_mem_access_ok;
	wire [9:0] rx2tx_mem_access_qno;
	wire rx2tx_mem_access_vld;
	wire rx2tx_rcvd_rocky_ack_eop_ok;
	wire rx2tx_rcvd_rocky_ack_eop_vld;
	wire [12:0] rx2tx_rcvd_rocky_ack_payload_length;
	wire rx2tx_rcvd_rocky_ack_port_no;
	wire rx2tx_rcvd_rocky_ack_rx_fifo_ovrn;
	wire rx2tx_rcvd_rocky_ack_vld;
	wire [4*8-1:0] rx2tx_rocky_ack_aeth;
	wire [12*8-1:0] rx2tx_rocky_ack_bth;
	wire rx2tx_rocky_ack_duplicate;
	wire rx2tx_rocky_ack_port_no;
	wire [31:0] rx2tx_rocky_ack_read_req_length;
	wire [63:0] rx2tx_rocky_ack_read_req_virt_addr;
	wire rx2tx_rocky_ack_vld;
	wire [63:0] rx_bm2axi_addr;
	wire [20:0] rx_bm2axi_id;
	wire [4:0] rx_bm2axi_len;
	wire rx_bm2axi_ordrd_rd_ind_rdy;
	wire [9:0] rx_bm2axi_qp_no;
	wire rx_bm2axi_rd_req;
	wire [1:0] rx_bm2axi_snp;
	wire rx_completed_queue_elements_decr;
	wire [9:0] rx_completed_queue_elements_decr_qno;
	wire rx_descr2axi_ordrd_wr_rspns_rdy;
	wire [63:0] rx_dma_wr2axi_addr;
	wire [255:0] rx_dma_wr2axi_data;
	wire [15:0] rx_dma_wr2axi_id;
	wire [4:0] rx_dma_wr2axi_len;
	wire rx_dma_wr2axi_ordrd_wr_rspns_rdy;
	wire [9:0] rx_dma_wr2axi_qp_no;
	wire [1:0] rx_dma_wr2axi_snp;
	wire [1:0] rx_dma_wr2axi_type;
	wire rx_dma_wr2axi_wr_req;
	wire [31:0] rx_dma_wr2axi_wr_strb;
	wire rx_fifo_overrun_intrpt;
	wire [1023:0] rx_no_of_completed_pkts_eq0;
	wire [1023:0] rx_no_of_completed_pkts_gt_thresh;
	wire rx_no_qe_intrpt;
	wire [9:0] rx_no_qe_intrpt_qno;
	wire rx_pkt_error_intrpt;
	wire [9:0] rx_pkt_error_intrpt_qno;
	wire [3:0] rx_pkt_error_intrpt_type;
	wire [1023:0] rx_pkt_with_se_received;
	wire rx_pp_tx_fifo_overrun_intrpt;
	wire rx_pp_tx_fifo_underrun_intrpt;
	wire rx_rnr_nack_intrpt;
	wire [9:0] rx_rnr_nack_intrpt_qno;
	wire [1023:0] rxq_thresh_event_intrpt;
	wire [31:0] slv2all_addr;
	wire [31:0] slv2all_data;
	wire slv2all_penable;
	wire slv2all_pwrite;
	wire slv2axi_psel;
	wire slv2rx_psel;
	wire slv2tx_psel;
	wire statistics2tx_timeout_rdy;
	wire [63:0] tx2axi_descr_addr;
	wire [100:0] tx2axi_descr_id;
	wire [4:0] tx2axi_descr_len;
	wire [9:0] tx2axi_descr_qp_no;
	wire tx2axi_descr_rd_req;
	wire [1:0] tx2axi_descr_snp;
	wire [63:0] tx2axi_pkt_addr;
	wire [63:0] tx2axi_pkt_id;
	wire tx2axi_pkt_is_rdma_write;
	wire [4:0] tx2axi_pkt_len;
	wire [9:0] tx2axi_pkt_qp_no;
	wire tx2axi_pkt_rd_req;
	wire [1:0] tx2axi_pkt_snp;
	wire [63:0] tx2axi_rdma_rd_addr;
	wire [15:0] tx2axi_rdma_rd_id;
	wire [4:0] tx2axi_rdma_rd_len;
	wire [9:0] tx2axi_rdma_rd_qp_no;
	wire tx2axi_rdma_rd_rd_req;
	wire [1:0] tx2axi_rdma_rd_snp;
	wire tx2rx_ack_fifo_full;
	wire [63:0] tx2rx_rcvd_read_rspns_local_host_addr;
	wire tx2rx_rcvd_read_rspns_ok;
	wire tx2rx_rcvd_read_rspns_vld;
	wire tx2rx_read_req_fifo_full;
	wire [31:0] tx2slv_prdata;
	wire tx2slv_pready;
	wire [9:0] tx2statistics_timeout_qno;
	wire tx2statistics_timeout_vld;
	wire tx_ack_reception_timeout_intrpt;
	wire [9:0] tx_ack_reception_timeout_intrpt_qno;
	wire tx_descr2axi_ordrd_rd_ind_rdy;
	wire tx_fifo_underrun_intrpt;
	wire [1023:0] tx_no_of_transmitted_pkts_eq0;
	wire [1023:0] tx_no_of_transmitted_pkts_gt_thresh;
	wire tx_pkt2axi_ordrd_rd_ind_rdy;
	wire tx_pkt_error_intrpt;
	wire [9:0] tx_pkt_error_intrpt_qno;
	wire [3:0] tx_pkt_error_intrpt_type;
	wire tx_pkt_retransmission_intrpt;
	wire [9:0] tx_pkt_retransmission_intrpt_qno;
	wire [1023:0] tx_pkt_with_notify_transmitted;
	wire tx_pp_rx_fifo_overrun_intrpt;
	wire tx_rdma_rd2axi_ordrd_rd_ind_rdy;

	// buf
	assign rdm2p_pfc_bus2[13:0] = 14'd0;

	// buf
	assign rdm2p_pfc_bus1[13:0] = 14'd0;

	// buf
	assign rdm2p_pfc_bus0[13:0] = 14'd0;

	// buf
	assign rams_parity_error_bus_[7:0] = 8'hFF;

	// buf
	assign clk = rdma_clk;

	// buf
	assign reset_ = rdma_reset_;

	// buf
	assign intrpt2axi_qp_no[9:0] = 10'd0;

	// buf
	assign rdm2p_global_xoff_ = 1'd0;

	// buf
	assign rdm2p_pfc_valid_[2:0] = 3'b111;

	// RAM_PARITY
	integer i11;
	reg [7:0] ram_no_with_parity_error_next;
	reg ram_parity_error_next;
	always @ (rams_parity_error_bus_) begin 
	  ram_parity_error_next              = 1'b0;
	  ram_no_with_parity_error_next[7:0] = 8'h0;
	  for (i11 = 0; i11 < NO_OF_RAMS; i11 = i11 + 1) begin 
	    if (rams_parity_error_bus_[i11] == 1'b0) begin 
	      ram_no_with_parity_error_next[7:0] = i11;
	      ram_parity_error_next              = 1'b1;
	    end
	  end
	end//always
	
	always @ (posedge clk or negedge reset_) begin 
	  if (!reset_) begin 
	    ram_no_with_parity_error[7:0] <= #0.1 8'h0;
	    ram_parity_error              <= #0.1 1'b0;
	  end
	  else begin 
	    ram_no_with_parity_error[7:0] <= #0.1 ram_no_with_parity_error_next[7:0];
	    ram_parity_error              <= #0.1 ram_parity_error_next;
	  end
	end//always

	rdma_apb2slv rdma_apb2slv (
		//Input Pins
       // Interface DEBUG Connections
        .interface_dbg_bus(interface_dbg_bus[4*325 +: 1*325]),
       // State Machines DEBUG Connections
        .sm_dbg_bus(sm_dbg_bus[56*8 +: 5*8]),
		.apb2rdm_paddr(apb2rdm_paddr[31:2]),
		.apb2rdm_penable(apb2rdm_penable),
		.apb2rdm_psel(apb2rdm_psel),
		.apb2rdm_pwdata(apb2rdm_pwdata[31:0]),
		.apb2rdm_pwrite(apb2rdm_pwrite),
		.axi2intrpt_ordrd_wr_rspns_vld(axi2intrpt_ordrd_wr_rspns_vld),
		.axi2intrpt_wr_ack(axi2intrpt_wr_ack),
		.axi2slv_prdata(axi2slv_prdata[31:0]),
		.axi2slv_pready(axi2slv_pready),
		.clk(clk),
		.gop_int_overrun(gop_int_overrun),
		.ram_no_with_parity_error(ram_no_with_parity_error[7:0]),
		.ram_parity_error(ram_parity_error),
		.reset_(reset_),
		.rx2slv_prdata(rx2slv_prdata[31:0]),
		.rx2slv_pready(rx2slv_pready),
		.rx2statistics_qno(rx2statistics_qno[9:0]),
		.rx2statistics_type(rx2statistics_type[3:0]),
		.rx2statistics_vld(rx2statistics_vld),
		.rx_completed_queue_elements_decr(rx_completed_queue_elements_decr),
		.rx_completed_queue_elements_decr_qno(rx_completed_queue_elements_decr_qno[9:0]),
		.rx_fifo_overrun_intrpt(rx_fifo_overrun_intrpt),
		.rx_no_of_completed_pkts_eq0(rx_no_of_completed_pkts_eq0[1023:0]),
		.rx_no_of_completed_pkts_gt_thresh(rx_no_of_completed_pkts_gt_thresh[1023:0]),
		.rx_no_qe_intrpt(rx_no_qe_intrpt),
		.rx_no_qe_intrpt_qno(rx_no_qe_intrpt_qno[9:0]),
		.rx_pkt_error_intrpt(rx_pkt_error_intrpt),
		.rx_pkt_error_intrpt_qno(rx_pkt_error_intrpt_qno[9:0]),
		.rx_pkt_error_intrpt_type(rx_pkt_error_intrpt_type[3:0]),
		.rx_pkt_with_se_received(rx_pkt_with_se_received[1023:0]),
		.rx_pp_tx_fifo_overrun_intrpt(rx_pp_tx_fifo_overrun_intrpt),
		.rx_pp_tx_fifo_underrun_intrpt(rx_pp_tx_fifo_underrun_intrpt),
		.rx_rnr_nack_intrpt(rx_rnr_nack_intrpt),
		.rx_rnr_nack_intrpt_qno(rx_rnr_nack_intrpt_qno[9:0]),
		.rxq_thresh_event_intrpt(rxq_thresh_event_intrpt[1023:0]),
		.tx2slv_prdata(tx2slv_prdata[31:0]),
		.tx2slv_pready(tx2slv_pready),
		.tx2statistics_timeout_qno(tx2statistics_timeout_qno[9:0]),
		.tx2statistics_timeout_vld(tx2statistics_timeout_vld),
		.tx_ack_reception_timeout_intrpt(tx_ack_reception_timeout_intrpt),
		.tx_ack_reception_timeout_intrpt_qno(tx_ack_reception_timeout_intrpt_qno[9:0]),
		.tx_fifo_underrun_intrpt(tx_fifo_underrun_intrpt),
		.tx_no_of_transmitted_pkts_eq0(tx_no_of_transmitted_pkts_eq0[1023:0]),
		.tx_no_of_transmitted_pkts_gt_thresh(tx_no_of_transmitted_pkts_gt_thresh[1023:0]),
		.tx_pkt_error_intrpt(tx_pkt_error_intrpt),
		.tx_pkt_error_intrpt_qno(tx_pkt_error_intrpt_qno[9:0]),
		.tx_pkt_error_intrpt_type(tx_pkt_error_intrpt_type[3:0]),
		.tx_pkt_retransmission_intrpt(tx_pkt_retransmission_intrpt),
		.tx_pkt_retransmission_intrpt_qno(tx_pkt_retransmission_intrpt_qno[9:0]),
		.tx_pkt_with_notify_transmitted(tx_pkt_with_notify_transmitted[1023:0]),
		.tx_pp_rx_fifo_overrun_intrpt(tx_pp_rx_fifo_overrun_intrpt),
		//Output Pins
		.conf_axi_max_no_of_data_phases(conf_axi_max_no_of_data_phases[5:0]),
		.conf_axi_max_reads(conf_axi_max_reads[6:0]),
		.conf_axi_max_writes(conf_axi_max_writes[6:0]),
		.conf_credit_en(conf_credit_en),
		.conf_p0_dsa_long(conf_p0_dsa_long),
		.conf_p0_dsa_short(conf_p0_dsa_short),
		.conf_p0_mac_addr(conf_p0_mac_addr[47:0]),
		.conf_p0_mrvl_hdr(conf_p0_mrvl_hdr),
		.conf_p0_mtu(conf_p0_mtu[13:0]),
		.conf_p1_dsa_long(conf_p1_dsa_long),
		.conf_p1_dsa_short(conf_p1_dsa_short),
		.conf_p1_mac_addr(conf_p1_mac_addr[47:0]),
		.conf_p1_mrvl_hdr(conf_p1_mrvl_hdr),
		.conf_p1_mtu(conf_p1_mtu[13:0]),
		.conf_p2_dsa_long(conf_p2_dsa_long),
		.conf_p2_dsa_short(conf_p2_dsa_short),
		.conf_p2_mac_addr(conf_p2_mac_addr[47:0]),
		.conf_p2_mrvl_hdr(conf_p2_mrvl_hdr),
		.conf_p2_mtu(conf_p2_mtu[13:0]),
		.conf_port_active(conf_port_active[2:0]),
		.conf_rocky_udp_port_no(conf_rocky_udp_port_no[15:0]),
		.conf_single_pkt_retry(conf_single_pkt_retry),
		.conf_tx_fifo_thresh(conf_tx_fifo_thresh[13:5]),
		.intrpt2axi_addr(intrpt2axi_addr[63:0]),
		.intrpt2axi_data(intrpt2axi_data[255:0]),
		.intrpt2axi_id(intrpt2axi_id[15:0]),
		.intrpt2axi_len(intrpt2axi_len[4:0]),
		.intrpt2axi_ordrd_wr_rspns_rdy(intrpt2axi_ordrd_wr_rspns_rdy),
		.intrpt2axi_snp(intrpt2axi_snp[1:0]),
		.intrpt2axi_wr_req(intrpt2axi_wr_req),
		.intrpt2axi_wr_strb(intrpt2axi_wr_strb[31:0]),
		.rdm2apb_prdata(rdm2apb_prdata[31:0]),
		.rdm2apb_pready(rdm2apb_pready),
		.slv2all_addr(slv2all_addr[31:0]),
		.slv2all_data(slv2all_data[31:0]),
		.slv2all_penable(slv2all_penable),
		.slv2all_pwrite(slv2all_pwrite),
		.slv2axi_psel(slv2axi_psel),
		.slv2rx_psel(slv2rx_psel),
		.slv2tx_psel(slv2tx_psel),
		.statistics2tx_timeout_rdy(statistics2tx_timeout_rdy)
	);

	rdma_axi rdma_axi (
		//Input Pins
       // State Machines DEBUG Connections
        .sm_dbg_bus(sm_dbg_bus[50*8 +: 6*8]),
		.axi2rdm_arready(axi2rdm_arready),
		.axi2rdm_awready(axi2rdm_awready),
		.axi2rdm_bid(axi2rdm_bid[5:0]),
		.axi2rdm_bresp(axi2rdm_bresp[1:0]),
		.axi2rdm_bvalid(axi2rdm_bvalid),
		.axi2rdm_rdata(axi2rdm_rdata[255:0]),
		.axi2rdm_rid(axi2rdm_rid[5:0]),
		.axi2rdm_rlast(axi2rdm_rlast),
		.axi2rdm_rresp(axi2rdm_rresp[1:0]),
		.axi2rdm_rvalid(axi2rdm_rvalid),
		.axi2rdm_wready(axi2rdm_wready),
		.clk(clk),
		.conf_axi_max_reads(conf_axi_max_reads[6:0]),
		.conf_axi_max_writes(conf_axi_max_writes[6:0]),
		.intrpt2axi_addr(intrpt2axi_addr[63:0]),
		.intrpt2axi_data(intrpt2axi_data[255:0]),
		.intrpt2axi_id(intrpt2axi_id[15:0]),
		.intrpt2axi_len(intrpt2axi_len[4:0]),
		.intrpt2axi_ordrd_wr_rspns_rdy(intrpt2axi_ordrd_wr_rspns_rdy),
		.intrpt2axi_qp_no(intrpt2axi_qp_no[9:0]),
		.intrpt2axi_snp(intrpt2axi_snp[1:0]),
		.intrpt2axi_wr_req(intrpt2axi_wr_req),
		.intrpt2axi_wr_strb(intrpt2axi_wr_strb[31:0]),
		.reset_(reset_),
		.rx2axi_descr_addr(rx2axi_descr_addr[63:0]),
		.rx2axi_descr_data(rx2axi_descr_data[255:0]),
		.rx2axi_descr_id(rx2axi_descr_id[15:0]),
		.rx2axi_descr_len(rx2axi_descr_len[4:0]),
		.rx2axi_descr_qp_no(rx2axi_descr_qp_no[9:0]),
		.rx2axi_descr_snp(rx2axi_descr_snp[1:0]),
		.rx2axi_descr_wr_req(rx2axi_descr_wr_req),
		.rx_bm2axi_addr(rx_bm2axi_addr[63:0]),
		.rx_bm2axi_id(rx_bm2axi_id[20:0]),
		.rx_bm2axi_len(rx_bm2axi_len[4:0]),
		.rx_bm2axi_ordrd_rd_ind_rdy(rx_bm2axi_ordrd_rd_ind_rdy),
		.rx_bm2axi_qp_no(rx_bm2axi_qp_no[9:0]),
		.rx_bm2axi_rd_req(rx_bm2axi_rd_req),
		.rx_bm2axi_snp(rx_bm2axi_snp[1:0]),
		.rx_descr2axi_ordrd_wr_rspns_rdy(rx_descr2axi_ordrd_wr_rspns_rdy),
		.rx_dma_wr2axi_addr(rx_dma_wr2axi_addr[63:0]),
		.rx_dma_wr2axi_data(rx_dma_wr2axi_data[255:0]),
		.rx_dma_wr2axi_id(rx_dma_wr2axi_id[15:0]),
		.rx_dma_wr2axi_len(rx_dma_wr2axi_len[4:0]),
		.rx_dma_wr2axi_ordrd_wr_rspns_rdy(rx_dma_wr2axi_ordrd_wr_rspns_rdy),
		.rx_dma_wr2axi_qp_no(rx_dma_wr2axi_qp_no[9:0]),
		.rx_dma_wr2axi_snp(rx_dma_wr2axi_snp[1:0]),
		.rx_dma_wr2axi_type(rx_dma_wr2axi_type[1:0]),
		.rx_dma_wr2axi_wr_req(rx_dma_wr2axi_wr_req),
		.rx_dma_wr2axi_wr_strb(rx_dma_wr2axi_wr_strb[31:0]),
		.slv2all_addr(slv2all_addr[31:0]),
		.slv2all_data(slv2all_data[31:0]),
		.slv2all_penable(slv2all_penable),
		.slv2all_pwrite(slv2all_pwrite),
		.slv2axi_psel(slv2axi_psel),
		.tx2axi_descr_addr(tx2axi_descr_addr[63:0]),
		.tx2axi_descr_id(tx2axi_descr_id[100:0]),
		.tx2axi_descr_len(tx2axi_descr_len[4:0]),
		.tx2axi_descr_qp_no(tx2axi_descr_qp_no[9:0]),
		.tx2axi_descr_rd_req(tx2axi_descr_rd_req),
		.tx2axi_descr_snp(tx2axi_descr_snp[1:0]),
		.tx2axi_pkt_addr(tx2axi_pkt_addr[63:0]),
		.tx2axi_pkt_id(tx2axi_pkt_id[63:0]),
		.tx2axi_pkt_is_rdma_write(tx2axi_pkt_is_rdma_write),
		.tx2axi_pkt_len(tx2axi_pkt_len[4:0]),
		.tx2axi_pkt_qp_no(tx2axi_pkt_qp_no[9:0]),
		.tx2axi_pkt_rd_req(tx2axi_pkt_rd_req),
		.tx2axi_pkt_snp(tx2axi_pkt_snp[1:0]),
		.tx2axi_rdma_rd_addr(tx2axi_rdma_rd_addr[63:0]),
		.tx2axi_rdma_rd_id(tx2axi_rdma_rd_id[15:0]),
		.tx2axi_rdma_rd_len(tx2axi_rdma_rd_len[4:0]),
		.tx2axi_rdma_rd_qp_no(tx2axi_rdma_rd_qp_no[9:0]),
		.tx2axi_rdma_rd_rd_req(tx2axi_rdma_rd_rd_req),
		.tx2axi_rdma_rd_snp(tx2axi_rdma_rd_snp[1:0]),
		.tx_descr2axi_ordrd_rd_ind_rdy(tx_descr2axi_ordrd_rd_ind_rdy),
		.tx_pkt2axi_ordrd_rd_ind_rdy(tx_pkt2axi_ordrd_rd_ind_rdy),
		.tx_rdma_rd2axi_ordrd_rd_ind_rdy(tx_rdma_rd2axi_ordrd_rd_ind_rdy),
		//Output Pins
		.axi2all_ordrd_rd_rspns_id(axi2all_ordrd_rd_rspns_id[100:0]),
		.axi2all_ordrd_wr_rspns_id(axi2all_ordrd_wr_rspns_id[15:0]),
		.axi2all_rd_rspns_data(axi2all_rd_rspns_data[255:0]),
		.axi2all_rd_rspns_dphase_count(axi2all_rd_rspns_dphase_count[4:0]),
		.axi2all_rd_rspns_id(axi2all_rd_rspns_id[100:0]),
		.axi2all_rd_rspns_last(axi2all_rd_rspns_last),
		.axi2intrpt_ordrd_wr_rspns_vld(axi2intrpt_ordrd_wr_rspns_vld),
		.axi2intrpt_wr_ack(axi2intrpt_wr_ack),
		.axi2rx_bm_ordrd_rd_ind_vld(axi2rx_bm_ordrd_rd_ind_vld),
		.axi2rx_bm_rd_ack(axi2rx_bm_rd_ack),
		.axi2rx_bm_rd_rspns_vld(axi2rx_bm_rd_rspns_vld),
		.axi2rx_descr_ordrd_wr_rspns_vld(axi2rx_descr_ordrd_wr_rspns_vld),
		.axi2rx_descr_wr_ack(axi2rx_descr_wr_ack),
		.axi2rx_dma_wr_ordrd_wr_rspns_vld(axi2rx_dma_wr_ordrd_wr_rspns_vld),
		.axi2rx_dma_wr_wr_ack(axi2rx_dma_wr_wr_ack),
		.axi2slv_prdata(axi2slv_prdata[31:0]),
		.axi2slv_pready(axi2slv_pready),
		.axi2tx_descr_ordrd_rd_ind_vld(axi2tx_descr_ordrd_rd_ind_vld),
		.axi2tx_descr_rd_ack(axi2tx_descr_rd_ack),
		.axi2tx_descr_rd_rspns_vld(axi2tx_descr_rd_rspns_vld),
		.axi2tx_pkt_ordrd_rd_ind_vld(axi2tx_pkt_ordrd_rd_ind_vld),
		.axi2tx_pkt_rd_ack(axi2tx_pkt_rd_ack),
		.axi2tx_pkt_rd_rspns_vld(axi2tx_pkt_rd_rspns_vld),
		.axi2tx_rdma_rd_ordrd_rd_ind_vld(axi2tx_rdma_rd_ordrd_rd_ind_vld),
		.axi2tx_rdma_rd_rd_ack(axi2tx_rdma_rd_rd_ack),
		.axi2tx_rdma_rd_rd_rspns_vld(axi2tx_rdma_rd_rd_rspns_vld),
		.rdm2axi_araddr(rdm2axi_araddr[63:0]),
		.rdm2axi_arburst(rdm2axi_arburst[1:0]),
		.rdm2axi_arcache(rdm2axi_arcache[3:0]),
		.rdm2axi_arid(rdm2axi_arid[5:0]),
		.rdm2axi_arlen(rdm2axi_arlen[4:0]),
		.rdm2axi_arlock(rdm2axi_arlock),
		.rdm2axi_armstr(rdm2axi_armstr[1:0]),
		.rdm2axi_arprot(rdm2axi_arprot),
		.rdm2axi_arqos(rdm2axi_arqos[3:0]),
		.rdm2axi_arsize(rdm2axi_arsize[2:0]),
		.rdm2axi_aruser(rdm2axi_aruser[15:0]),
		.rdm2axi_arvalid(rdm2axi_arvalid),
		.rdm2axi_awaddr(rdm2axi_awaddr[63:0]),
		.rdm2axi_awburst(rdm2axi_awburst[1:0]),
		.rdm2axi_awcache(rdm2axi_awcache[3:0]),
		.rdm2axi_awid(rdm2axi_awid[5:0]),
		.rdm2axi_awlen(rdm2axi_awlen[4:0]),
		.rdm2axi_awlock(rdm2axi_awlock),
		.rdm2axi_awmstr(rdm2axi_awmstr[1:0]),
		.rdm2axi_awprot(rdm2axi_awprot),
		.rdm2axi_awqos(rdm2axi_awqos[3:0]),
		.rdm2axi_awsize(rdm2axi_awsize[2:0]),
		.rdm2axi_awuser(rdm2axi_awuser[15:0]),
		.rdm2axi_awvalid(rdm2axi_awvalid),
		.rdm2axi_bready(rdm2axi_bready),
		.rdm2axi_rready(rdm2axi_rready),
		.rdm2axi_wdata(rdm2axi_wdata[255:0]),
		.rdm2axi_wid(rdm2axi_wid[5:0]),
		.rdm2axi_wlast(rdm2axi_wlast),
		.rdm2axi_wstrb(rdm2axi_wstrb[31:0]),
		.rdm2axi_wvalid(rdm2axi_wvalid)
	);

	rdma_rx rdma_rx (
		//Input Pins
       // Interface DEBUG Connections
        .interface_dbg_bus(interface_dbg_bus[3*325 +: 1*325]),
       // State Machines DEBUG Connections
        .sm_dbg_bus(sm_dbg_bus[25*8 +: 25*8]),
		.axi2all_ordrd_rd_rspns_id(axi2all_ordrd_rd_rspns_id[20:0]),
		.axi2all_ordrd_wr_rspns_id(axi2all_ordrd_wr_rspns_id[15:0]),
		.axi2all_rd_rspns_data(axi2all_rd_rspns_data[255:0]),
		.axi2all_rd_rspns_dphase_count(axi2all_rd_rspns_dphase_count[4:0]),
		.axi2all_rd_rspns_id(axi2all_rd_rspns_id[100:0]),
		.axi2rx_bm_ordrd_rd_ind_vld(axi2rx_bm_ordrd_rd_ind_vld),
		.axi2rx_bm_rd_ack(axi2rx_bm_rd_ack),
		.axi2rx_bm_rd_rspns_vld(axi2rx_bm_rd_rspns_vld),
		.axi2rx_descr_ordrd_wr_rspns_vld(axi2rx_descr_ordrd_wr_rspns_vld),
		.axi2rx_descr_wr_ack(axi2rx_descr_wr_ack),
		.axi2rx_dma_wr_ordrd_wr_rspns_vld(axi2rx_dma_wr_ordrd_wr_rspns_vld),
		.axi2rx_dma_wr_wr_ack(axi2rx_dma_wr_wr_ack),
		.axi2tx_descr_rd_rspns_vld(axi2tx_descr_rd_rspns_vld),
		.clk(clk),
		.conf_axi_max_no_of_data_phases(conf_axi_max_no_of_data_phases[5:0]),
		.conf_p0_dsa_long(conf_p0_dsa_long),
		.conf_p0_dsa_short(conf_p0_dsa_short),
		.conf_p0_mac_addr(conf_p0_mac_addr[47:0]),
		.conf_p0_mrvl_hdr(conf_p0_mrvl_hdr),
		.conf_p1_dsa_long(conf_p1_dsa_long),
		.conf_p1_dsa_short(conf_p1_dsa_short),
		.conf_p1_mac_addr(conf_p1_mac_addr[47:0]),
		.conf_p1_mrvl_hdr(conf_p1_mrvl_hdr),
		.conf_p2_dsa_long(conf_p2_dsa_long),
		.conf_p2_dsa_short(conf_p2_dsa_short),
		.conf_p2_mac_addr(conf_p2_mac_addr[47:0]),
		.conf_p2_mrvl_hdr(conf_p2_mrvl_hdr),
		.conf_rocky_udp_port_no(conf_rocky_udp_port_no[15:0]),
		.p02mem_rx_data(p02mem_rx_data[255:0]),
		.p02mem_rx_desc(p02mem_rx_desc[15:0]),
		.p02mem_rx_eop_(p02mem_rx_eop_),
		.p02mem_rx_load_(p02mem_rx_load_),
		.p02mem_rx_sop_(p02mem_rx_sop_),
		.p12mem_rx_data(p12mem_rx_data[255:0]),
		.p12mem_rx_desc(p12mem_rx_desc[15:0]),
		.p12mem_rx_eop_(p12mem_rx_eop_),
		.p12mem_rx_load_(p12mem_rx_load_),
		.p12mem_rx_sop_(p12mem_rx_sop_),
		.pa2mem_rx_data(pa2mem_rx_data[63:0]),
		.pa2mem_rx_desc(pa2mem_rx_desc[15:0]),
		.pa2mem_rx_eop_(pa2mem_rx_eop_),
		.pa2mem_rx_load_(pa2mem_rx_load_),
		.pa2mem_rx_sop_(pa2mem_rx_sop_),
		.pp2mem_tx_ready_(pp2mem_tx_ready_),
		.reset_(reset_),
		.slv2all_addr(slv2all_addr[31:0]),
		.slv2all_data(slv2all_data[31:0]),
		.slv2all_penable(slv2all_penable),
		.slv2all_pwrite(slv2all_pwrite),
		.slv2rx_psel(slv2rx_psel),
		.tx2rx_ack_fifo_full(tx2rx_ack_fifo_full),
		.tx2rx_rcvd_read_rspns_local_host_addr(tx2rx_rcvd_read_rspns_local_host_addr[63:0]),
		.tx2rx_rcvd_read_rspns_ok(tx2rx_rcvd_read_rspns_ok),
		.tx2rx_rcvd_read_rspns_vld(tx2rx_rcvd_read_rspns_vld),
		.tx2rx_read_req_fifo_full(tx2rx_read_req_fifo_full),
		//Output Pins
		.conf_p_keys(conf_p_keys[1024*16-1:0]),
		.conf_pmtu(conf_pmtu[1024*3-1:0]),
		.conf_qp_vld(conf_qp_vld[1023:0]),
		.gop_int_overrun(gop_int_overrun),
		.mem2p0_rx_ready_(mem2p0_rx_ready_),
		.mem2p1_rx_ready_(mem2p1_rx_ready_),
		.mem2pa_rx_ready_(mem2pa_rx_ready_),
		.mem2pp_tx_bad_crc_(mem2pp_tx_bad_crc_),
		.mem2pp_tx_data(mem2pp_tx_data[63:0]),
		.mem2pp_tx_desc(mem2pp_tx_desc[88:17]),
		.mem2pp_tx_eop_(mem2pp_tx_eop_),
		.mem2pp_tx_load_(mem2pp_tx_load_),
		.mem2pp_tx_mod(mem2pp_tx_mod[2:0]),
		.mem2pp_tx_sop_(mem2pp_tx_sop_),
		.rdm2p_pause_(rdm2p_pause_[2:0]),
		.rx2axi_descr_addr(rx2axi_descr_addr[63:0]),
		.rx2axi_descr_data(rx2axi_descr_data[255:0]),
		.rx2axi_descr_id(rx2axi_descr_id[15:0]),
		.rx2axi_descr_len(rx2axi_descr_len[4:0]),
		.rx2axi_descr_qp_no(rx2axi_descr_qp_no[9:0]),
		.rx2axi_descr_snp(rx2axi_descr_snp[1:0]),
		.rx2axi_descr_wr_req(rx2axi_descr_wr_req),
		.rx2slv_prdata(rx2slv_prdata[31:0]),
		.rx2slv_pready(rx2slv_pready),
		.rx2statistics_qno(rx2statistics_qno[9:0]),
		.rx2statistics_type(rx2statistics_type[3:0]),
		.rx2statistics_vld(rx2statistics_vld),
		.rx2tx_mem_access_line_no(rx2tx_mem_access_line_no[7:0]),
		.rx2tx_mem_access_ok(rx2tx_mem_access_ok),
		.rx2tx_mem_access_qno(rx2tx_mem_access_qno[9:0]),
		.rx2tx_mem_access_vld(rx2tx_mem_access_vld),
		.rx2tx_rcvd_rocky_ack_eop_ok(rx2tx_rcvd_rocky_ack_eop_ok),
		.rx2tx_rcvd_rocky_ack_eop_vld(rx2tx_rcvd_rocky_ack_eop_vld),
		.rx2tx_rcvd_rocky_ack_payload_length(rx2tx_rcvd_rocky_ack_payload_length[12:0]),
		.rx2tx_rcvd_rocky_ack_port_no(rx2tx_rcvd_rocky_ack_port_no),
		.rx2tx_rcvd_rocky_ack_rx_fifo_ovrn(rx2tx_rcvd_rocky_ack_rx_fifo_ovrn),
		.rx2tx_rcvd_rocky_ack_vld(rx2tx_rcvd_rocky_ack_vld),
		.rx2tx_rocky_ack_aeth(rx2tx_rocky_ack_aeth[4*8-1:0]),
		.rx2tx_rocky_ack_bth(rx2tx_rocky_ack_bth[12*8-1:0]),
		.rx2tx_rocky_ack_duplicate(rx2tx_rocky_ack_duplicate),
		.rx2tx_rocky_ack_port_no(rx2tx_rocky_ack_port_no),
		.rx2tx_rocky_ack_read_req_length(rx2tx_rocky_ack_read_req_length[31:0]),
		.rx2tx_rocky_ack_read_req_virt_addr(rx2tx_rocky_ack_read_req_virt_addr[63:0]),
		.rx2tx_rocky_ack_vld(rx2tx_rocky_ack_vld),
		.rx_bm2axi_addr(rx_bm2axi_addr[63:0]),
		.rx_bm2axi_id(rx_bm2axi_id[20:0]),
		.rx_bm2axi_len(rx_bm2axi_len[4:0]),
		.rx_bm2axi_ordrd_rd_ind_rdy(rx_bm2axi_ordrd_rd_ind_rdy),
		.rx_bm2axi_qp_no(rx_bm2axi_qp_no[9:0]),
		.rx_bm2axi_rd_req(rx_bm2axi_rd_req),
		.rx_bm2axi_snp(rx_bm2axi_snp[1:0]),
		.rx_completed_queue_elements_decr(rx_completed_queue_elements_decr),
		.rx_completed_queue_elements_decr_qno(rx_completed_queue_elements_decr_qno[9:0]),
		.rx_descr2axi_ordrd_wr_rspns_rdy(rx_descr2axi_ordrd_wr_rspns_rdy),
		.rx_dma_wr2axi_addr(rx_dma_wr2axi_addr[63:0]),
		.rx_dma_wr2axi_data(rx_dma_wr2axi_data[255:0]),
		.rx_dma_wr2axi_id(rx_dma_wr2axi_id[15:0]),
		.rx_dma_wr2axi_len(rx_dma_wr2axi_len[4:0]),
		.rx_dma_wr2axi_ordrd_wr_rspns_rdy(rx_dma_wr2axi_ordrd_wr_rspns_rdy),
		.rx_dma_wr2axi_qp_no(rx_dma_wr2axi_qp_no[9:0]),
		.rx_dma_wr2axi_snp(rx_dma_wr2axi_snp[1:0]),
		.rx_dma_wr2axi_type(rx_dma_wr2axi_type[1:0]),
		.rx_dma_wr2axi_wr_req(rx_dma_wr2axi_wr_req),
		.rx_dma_wr2axi_wr_strb(rx_dma_wr2axi_wr_strb[31:0]),
		.rx_fifo_overrun_intrpt(rx_fifo_overrun_intrpt),
		.rx_no_of_completed_pkts_eq0(rx_no_of_completed_pkts_eq0[1023:0]),
		.rx_no_of_completed_pkts_gt_thresh(rx_no_of_completed_pkts_gt_thresh[1023:0]),
		.rx_no_qe_intrpt(rx_no_qe_intrpt),
		.rx_no_qe_intrpt_qno(rx_no_qe_intrpt_qno[9:0]),
		.rx_pkt_error_intrpt(rx_pkt_error_intrpt),
		.rx_pkt_error_intrpt_qno(rx_pkt_error_intrpt_qno[9:0]),
		.rx_pkt_error_intrpt_type(rx_pkt_error_intrpt_type[3:0]),
		.rx_pkt_with_se_received(rx_pkt_with_se_received[1023:0]),
		.rx_pp_tx_fifo_overrun_intrpt(rx_pp_tx_fifo_overrun_intrpt),
		.rx_pp_tx_fifo_underrun_intrpt(rx_pp_tx_fifo_underrun_intrpt),
		.rx_rnr_nack_intrpt(rx_rnr_nack_intrpt),
		.rx_rnr_nack_intrpt_qno(rx_rnr_nack_intrpt_qno[9:0]),
		.rxq_thresh_event_intrpt(rxq_thresh_event_intrpt[1023:0])
	);

	rdma_tx rdma_tx (
		//Input Pins
       // Interface DEBUG Connections
        .interface_dbg_bus(interface_dbg_bus[2*325 +: 1*325]),
       // State Machines DEBUG Connections
        .sm_dbg_bus(sm_dbg_bus[0*8 +: 25*8]),
		.axi2all_ordrd_rd_rspns_id(axi2all_ordrd_rd_rspns_id[100:0]),
		.axi2all_rd_rspns_data(axi2all_rd_rspns_data[255:0]),
		.axi2all_rd_rspns_dphase_count(axi2all_rd_rspns_dphase_count[4:0]),
		.axi2all_rd_rspns_id(axi2all_rd_rspns_id[100:0]),
		.axi2all_rd_rspns_last(axi2all_rd_rspns_last),
		.axi2tx_descr_ordrd_rd_ind_vld(axi2tx_descr_ordrd_rd_ind_vld),
		.axi2tx_descr_rd_ack(axi2tx_descr_rd_ack),
		.axi2tx_descr_rd_rspns_vld(axi2tx_descr_rd_rspns_vld),
		.axi2tx_pkt_ordrd_rd_ind_vld(axi2tx_pkt_ordrd_rd_ind_vld),
		.axi2tx_pkt_rd_ack(axi2tx_pkt_rd_ack),
		.axi2tx_pkt_rd_rspns_vld(axi2tx_pkt_rd_rspns_vld),
		.axi2tx_rdma_rd_ordrd_rd_ind_vld(axi2tx_rdma_rd_ordrd_rd_ind_vld),
		.axi2tx_rdma_rd_rd_ack(axi2tx_rdma_rd_rd_ack),
		.axi2tx_rdma_rd_rd_rspns_vld(axi2tx_rdma_rd_rd_rspns_vld),
		.clk(clk),
		.conf_axi_max_no_of_data_phases(conf_axi_max_no_of_data_phases[5:0]),
		.conf_credit_en(conf_credit_en),
		.conf_p0_dsa_long(conf_p0_dsa_long),
		.conf_p0_dsa_short(conf_p0_dsa_short),
		.conf_p0_mac_addr(conf_p0_mac_addr[47:0]),
		.conf_p0_mrvl_hdr(conf_p0_mrvl_hdr),
		.conf_p0_mtu(conf_p0_mtu[13:0]),
		.conf_p1_dsa_long(conf_p1_dsa_long),
		.conf_p1_dsa_short(conf_p1_dsa_short),
		.conf_p1_mac_addr(conf_p1_mac_addr[47:0]),
		.conf_p1_mrvl_hdr(conf_p1_mrvl_hdr),
		.conf_p1_mtu(conf_p1_mtu[13:0]),
		.conf_p2_dsa_long(conf_p2_dsa_long),
		.conf_p2_dsa_short(conf_p2_dsa_short),
		.conf_p2_mrvl_hdr(conf_p2_mrvl_hdr),
		.conf_p2_mtu(conf_p2_mtu[13:0]),
		.conf_p_keys(conf_p_keys[1024*16-1:0]),
		.conf_pmtu(conf_pmtu[1024*3-1:0]),
		.conf_port_active(conf_port_active[2:0]),
		.conf_qp_vld(conf_qp_vld[1023:0]),
		.conf_rocky_udp_port_no(conf_rocky_udp_port_no[15:0]),
		.conf_single_pkt_retry(conf_single_pkt_retry),
		.conf_tx_fifo_thresh(conf_tx_fifo_thresh[13:5]),
		.p02mem_tx_ready_(p02mem_tx_ready_),
		.p12mem_tx_ready_(p12mem_tx_ready_),
		.pa2mem_tx_ready_(pa2mem_tx_ready_),
		.pp2mem_rx_data(pp2mem_rx_data[63:0]),
		.pp2mem_rx_desc(pp2mem_rx_desc[15:0]),
		.pp2mem_rx_eop_(pp2mem_rx_eop_),
		.pp2mem_rx_load_(pp2mem_rx_load_),
		.pp2mem_rx_sop_(pp2mem_rx_sop_),
		.pp2mem_sop_rx_desc(pp2mem_sop_rx_desc[39:7]),
		.reset_(reset_),
		.rx2tx_mem_access_line_no(rx2tx_mem_access_line_no[7:0]),
		.rx2tx_mem_access_ok(rx2tx_mem_access_ok),
		.rx2tx_mem_access_qno(rx2tx_mem_access_qno[9:0]),
		.rx2tx_mem_access_vld(rx2tx_mem_access_vld),
		.rx2tx_rcvd_rocky_ack_eop_ok(rx2tx_rcvd_rocky_ack_eop_ok),
		.rx2tx_rcvd_rocky_ack_eop_vld(rx2tx_rcvd_rocky_ack_eop_vld),
		.rx2tx_rcvd_rocky_ack_payload_length(rx2tx_rcvd_rocky_ack_payload_length[12:0]),
		.rx2tx_rcvd_rocky_ack_port_no(rx2tx_rcvd_rocky_ack_port_no),
		.rx2tx_rcvd_rocky_ack_rx_fifo_ovrn(rx2tx_rcvd_rocky_ack_rx_fifo_ovrn),
		.rx2tx_rcvd_rocky_ack_vld(rx2tx_rcvd_rocky_ack_vld),
		.rx2tx_rocky_ack_aeth(rx2tx_rocky_ack_aeth[4*8-1:0]),
		.rx2tx_rocky_ack_bth(rx2tx_rocky_ack_bth[12*8-1:0]),
		.rx2tx_rocky_ack_duplicate(rx2tx_rocky_ack_duplicate),
		.rx2tx_rocky_ack_port_no(rx2tx_rocky_ack_port_no),
		.rx2tx_rocky_ack_read_req_length(rx2tx_rocky_ack_read_req_length[31:0]),
		.rx2tx_rocky_ack_read_req_virt_addr(rx2tx_rocky_ack_read_req_virt_addr[63:0]),
		.rx2tx_rocky_ack_vld(rx2tx_rocky_ack_vld),
		.slv2all_addr(slv2all_addr[31:0]),
		.slv2all_data(slv2all_data[31:0]),
		.slv2all_penable(slv2all_penable),
		.slv2all_pwrite(slv2all_pwrite),
		.slv2tx_psel(slv2tx_psel),
		.statistics2tx_timeout_rdy(statistics2tx_timeout_rdy),
		//Output Pins
		.mem2p0_tx_bad_crc_(mem2p0_tx_bad_crc_),
		.mem2p0_tx_data(mem2p0_tx_data[255:0]),
		.mem2p0_tx_desc(mem2p0_tx_desc[88:17]),
		.mem2p0_tx_eop_(mem2p0_tx_eop_),
		.mem2p0_tx_load_(mem2p0_tx_load_),
		.mem2p0_tx_mod(mem2p0_tx_mod[4:0]),
		.mem2p0_tx_sop_(mem2p0_tx_sop_),
		.mem2p1_tx_bad_crc_(mem2p1_tx_bad_crc_),
		.mem2p1_tx_data(mem2p1_tx_data[255:0]),
		.mem2p1_tx_desc(mem2p1_tx_desc[88:17]),
		.mem2p1_tx_eop_(mem2p1_tx_eop_),
		.mem2p1_tx_load_(mem2p1_tx_load_),
		.mem2p1_tx_mod(mem2p1_tx_mod[4:0]),
		.mem2p1_tx_sop_(mem2p1_tx_sop_),
		.mem2pa_tx_bad_crc_(mem2pa_tx_bad_crc_),
		.mem2pa_tx_data(mem2pa_tx_data[63:0]),
		.mem2pa_tx_desc(mem2pa_tx_desc[88:17]),
		.mem2pa_tx_eop_(mem2pa_tx_eop_),
		.mem2pa_tx_load_(mem2pa_tx_load_),
		.mem2pa_tx_mod(mem2pa_tx_mod[2:0]),
		.mem2pa_tx_sop_(mem2pa_tx_sop_),
		.mem2pp_rx_ready_(mem2pp_rx_ready_),
		.tx2axi_descr_addr(tx2axi_descr_addr[63:0]),
		.tx2axi_descr_id(tx2axi_descr_id[100:0]),
		.tx2axi_descr_len(tx2axi_descr_len[4:0]),
		.tx2axi_descr_qp_no(tx2axi_descr_qp_no[9:0]),
		.tx2axi_descr_rd_req(tx2axi_descr_rd_req),
		.tx2axi_descr_snp(tx2axi_descr_snp[1:0]),
		.tx2axi_pkt_addr(tx2axi_pkt_addr[63:0]),
		.tx2axi_pkt_id(tx2axi_pkt_id[63:0]),
		.tx2axi_pkt_is_rdma_write(tx2axi_pkt_is_rdma_write),
		.tx2axi_pkt_len(tx2axi_pkt_len[4:0]),
		.tx2axi_pkt_qp_no(tx2axi_pkt_qp_no[9:0]),
		.tx2axi_pkt_rd_req(tx2axi_pkt_rd_req),
		.tx2axi_pkt_snp(tx2axi_pkt_snp[1:0]),
		.tx2axi_rdma_rd_addr(tx2axi_rdma_rd_addr[63:0]),
		.tx2axi_rdma_rd_id(tx2axi_rdma_rd_id[15:0]),
		.tx2axi_rdma_rd_len(tx2axi_rdma_rd_len[4:0]),
		.tx2axi_rdma_rd_qp_no(tx2axi_rdma_rd_qp_no[9:0]),
		.tx2axi_rdma_rd_rd_req(tx2axi_rdma_rd_rd_req),
		.tx2axi_rdma_rd_snp(tx2axi_rdma_rd_snp[1:0]),
		.tx2rx_ack_fifo_full(tx2rx_ack_fifo_full),
		.tx2rx_rcvd_read_rspns_local_host_addr(tx2rx_rcvd_read_rspns_local_host_addr[63:0]),
		.tx2rx_rcvd_read_rspns_ok(tx2rx_rcvd_read_rspns_ok),
		.tx2rx_rcvd_read_rspns_vld(tx2rx_rcvd_read_rspns_vld),
		.tx2rx_read_req_fifo_full(tx2rx_read_req_fifo_full),
		.tx2slv_prdata(tx2slv_prdata[31:0]),
		.tx2slv_pready(tx2slv_pready),
		.tx2statistics_timeout_qno(tx2statistics_timeout_qno[9:0]),
		.tx2statistics_timeout_vld(tx2statistics_timeout_vld),
		.tx_ack_reception_timeout_intrpt(tx_ack_reception_timeout_intrpt),
		.tx_ack_reception_timeout_intrpt_qno(tx_ack_reception_timeout_intrpt_qno[9:0]),
		.tx_descr2axi_ordrd_rd_ind_rdy(tx_descr2axi_ordrd_rd_ind_rdy),
		.tx_fifo_underrun_intrpt(tx_fifo_underrun_intrpt),
		.tx_no_of_transmitted_pkts_eq0(tx_no_of_transmitted_pkts_eq0[1023:0]),
		.tx_no_of_transmitted_pkts_gt_thresh(tx_no_of_transmitted_pkts_gt_thresh[1023:0]),
		.tx_pkt2axi_ordrd_rd_ind_rdy(tx_pkt2axi_ordrd_rd_ind_rdy),
		.tx_pkt_error_intrpt(tx_pkt_error_intrpt),
		.tx_pkt_error_intrpt_qno(tx_pkt_error_intrpt_qno[9:0]),
		.tx_pkt_error_intrpt_type(tx_pkt_error_intrpt_type[3:0]),
		.tx_pkt_retransmission_intrpt(tx_pkt_retransmission_intrpt),
		.tx_pkt_retransmission_intrpt_qno(tx_pkt_retransmission_intrpt_qno[9:0]),
		.tx_pkt_with_notify_transmitted(tx_pkt_with_notify_transmitted[1023:0]),
		.tx_pp_rx_fifo_overrun_intrpt(tx_pp_rx_fifo_overrun_intrpt),
		.tx_rdma_rd2axi_ordrd_rd_ind_rdy(tx_rdma_rd2axi_ordrd_rd_ind_rdy)
	);
       assign interface_dbg_bus[0*325+ 0+:1] = p02mem_rx_sop_;
       assign interface_dbg_bus[0*325+ 1+:1] = p02mem_rx_eop_;
       assign interface_dbg_bus[0*325+ 2+:1] = p02mem_rx_load_;
       assign interface_dbg_bus[0*325+ 3+:1] = mem2p0_rx_ready_;
       assign interface_dbg_bus[0*325+ 4+:16] = p02mem_rx_desc[15:0];
       assign interface_dbg_bus[0*325+ 20+:256] = p02mem_rx_data[255:0];
       assign interface_dbg_bus[0*325+ 276 +: 49] = {49{1'b0}};
       assign interface_dbg_bus[1*325+ 0+:1] = mem2p0_tx_load_;
       assign interface_dbg_bus[1*325+ 1+:1] = p02mem_tx_ready_;
       assign interface_dbg_bus[1*325+ 2+:1] = mem2p0_tx_sop_;
       assign interface_dbg_bus[1*325+ 3+:1] = mem2p0_tx_eop_;
       assign interface_dbg_bus[1*325+ 4+:1] = mem2p0_tx_bad_crc_;
       assign interface_dbg_bus[1*325+ 5+:5] = mem2p0_tx_mod[4:0];
       assign interface_dbg_bus[1*325+ 10+:256] = mem2p0_tx_data[255:0];
       assign interface_dbg_bus[1*325+ 266 +: 59] = {59{1'b0}};
endmodule
